create_clock -add -name sys_clk_pin -period 10.00 -waveform {0 5} [get_ports {clk}]

set_property IOSTANDARD LVCMOS33 [get_ports {clk}]
set_property PACKAGE_PIN E3 [get_ports {clk}]

set_property PACKAGE_PIN J15 [get_ports {data_in[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_in[0]}]
set_property PACKAGE_PIN L16 [get_ports {data_in[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_in[1]}]
set_property PACKAGE_PIN M13 [get_ports {data_in[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_in[2]}]
set_property PACKAGE_PIN R15 [get_ports {data_in[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_in[3]}]
set_property PACKAGE_PIN R17 [get_ports {data_in[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_in[4]}]
set_property PACKAGE_PIN T18 [get_ports {data_in[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_in[5]}]
set_property PACKAGE_PIN U18 [get_ports {data_in[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_in[6]}]
set_property PACKAGE_PIN R13 [get_ports {data_in[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_in[7]}]
set_property PACKAGE_PIN T8 [get_ports {data_in[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_in[8]}]
set_property PACKAGE_PIN U8 [get_ports {data_in[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_in[9]}]
set_property PACKAGE_PIN R16 [get_ports {data_in[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_in[10]}]
set_property PACKAGE_PIN T13 [get_ports {data_in[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_in[11]}]
set_property PACKAGE_PIN H6 [get_ports {data_in[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_in[12]}]
set_property PACKAGE_PIN U12 [get_ports {data_in[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_in[13]}]
set_property PACKAGE_PIN U11 [get_ports {data_in[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_in[14]}]
set_property PACKAGE_PIN V10 [get_ports {data_in[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_in[15]}]

set_property PACKAGE_PIN N17 [get_ports {btn_in}]
set_property IOSTANDARD LVCMOS33 [get_ports {btn_in}]

set_property PACKAGE_PIN P17 [get_ports {btn_nxt}]
set_property IOSTANDARD LVCMOS33 [get_ports {btn_nxt}]

set_property PACKAGE_PIN M17 [get_ports {btn_rst}]
set_property IOSTANDARD LVCMOS33 [get_ports {btn_rst}]

set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN J17} [get_ports {AN[0]}]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN J18} [get_ports {AN[1]}]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN T9} [get_ports {AN[2]}]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN J14} [get_ports {AN[3]}]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN P14} [get_ports {AN[4]}]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN T14} [get_ports {AN[5]}]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN K2} [get_ports {AN[6]}]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN U13} [get_ports {AN[7]}]

set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN T10} [get_ports {SEG[0]}]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN R10} [get_ports {SEG[1]}]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN K16} [get_ports {SEG[2]}]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN K13} [get_ports {SEG[3]}]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN P15} [get_ports {SEG[4]}]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN T11} [get_ports {SEG[5]}]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN L18} [get_ports {SEG[6]}]

set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN H17} [get_ports {err_out[0]}];  
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN K15} [get_ports {err_out[1]}];